export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REGISTER_USER_REQUEST = 'AUTH_REGISTER_USER_REQUEST';
export const AUTH_REGISTER_USER_SUCCESS = 'AUTH_REGISTER_USER_SUCCESS';
export const AUTH_REGISTER_USER_ERROR = 'AUTH_REGISTER_USER_ERROR';
