export const GET_TRIP_REQUEST = 'GET_TRIP_REQUEST';
export const GET_TRIP_SUCCESS = 'GET_TRIP_SUCCESS';
export const GET_TRIP_ERROR = 'GET_TRIP_ERROR';
export const TRIP_INTERCEPTOR = 'TRIP_INTERCEPTOR';
export const TRIPS_ROUTER = 'TRIPS_ROUTER'
